### ISSUE TITLE
Missing something-something-v1-baseline

### ISSUE THREAD

**Issue by gongbudaizhe** [TwentyBN/something-something-v2-baseline#5]
Hi, 

Thanks for your effort, great starting point for the something-something dataset!

I notice there is also a baseline for some-something-v1 in the leaderboard :
> https://github.com/esc/smth-smth-baseline/tree/train_004
> smth-smth-baseline with dropout 

However, the link is dead and I couldn't find it anywhere : (

Can you provide the baseline for v1 too?

**Comment by raghavgoyal14** [comment]
Hi Li,

Unfortunately, we didn't release baseline code for version 1 of the dataset as we wish users to switch over to the newer version.

For v1, you can use this repo with a different data loader (as v1 uses jpeg images instead of webm videos)
You can take inspiration from: https://github.com/TwentyBN/GulpIO-benchmarks/blob/master/data_loader_jpeg.py
And you also have to modify `data_parser.py`

Hope this helps!

**Comment by gongbudaizhe** [comment]
I see. Thank you!

**Comment by chen-ming2019** [comment]
@raghavgoyal14 Hi, I downloaded the something-something v1 and v2 datasets respectively. But when I unziped them, an error named 'unkown the end error' always occured .Because of the error ,I only got some part of datas in the datasets. Do you know how to solve the problem?

**Comment by Fazlik995** [comment]
@chen-ming2019, did you solve the problem? I have the same issue?

**Comment by tamamha** [comment]
@Fazlik995 I also have the same problem , Did you solve it ?
